### ISSUE TITLE
Kanban Board setup

### ISSUE THREAD

**Issue by nottherealalanturing** [divinecharlotte/Recipe-app#7]
https://github.com/users/divinecharlotte/projects/2
This project has been assigned to a team of two (@divinecharlotte  and @nottherealalanturing ).

**Comment by prolajumokeoni** [comment]
Hi @nottherealalanturing and @divinecharlotte 
- The last reviewer left a comment on the [food list](https://github.com/divinecharlotte/Recipe-app/issues/2#issuecomment-1266610306) card, kindly move the points for each card to the beginning of the card it should come before the description, this would be better to see the points without opening the card

**Comment by nottherealalanturing** [comment]
@prolajumokeoni okay, will do that.

**Comment by prolajumokeoni** [comment]
Hi @nottherealalanturing  and @divinecharlotte 

Your kanban board is complete!  There is nothing else to say other than... it's time to  start your project :shipit: 
Congratulations! 🎉 
## Highlights
 
- Good  Kanban board setup 👏🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Kindly add a card for setting up  testing libraries, this can be a group task 👍🏿  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
Hi @nottherealalanturing  and @divinecharlotte 

Your kanban board is complete!  There is nothing else to say other than... it's time to  start your project :shipit: 
Congratulations! 🎉 
## Highlights
 
- Good  Kanban board setup 👏🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Kindly add a card for testing, this can be a group task 👍🏿  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
